repos:
  - repo: local
    hooks:
      - id: backend-check
        name: backend typecheck
        entry: just backend::check
        language: system
        types: [python]
        pass_filenames: false

      - id: backend-test
        name: backend typecheck
        entry: just backend::test
        language: system
        types: [python]
        pass_filenames: false

      - id: frontend-lint
        name: frontend lint
        entry: just frontend::check
        language: system
        files: ^frontend/src/
        pass_filenames: false

      - id: gen-oapi
        name: generate openapi schema
        entry: just gen-api-schema
        language: system
        pass_filenames: false
