repos:
  - repo: local
    hooks:
      - id: backend-test
        name: backend test
        entry: just backend::test
        language: system
        types: [python]
        pass_filenames: false

      - id: frontend-test
        name: frontend test
        entry: just frontend::test
        language: system
        files: ^frontend/src/
        pass_filenames: false

      - id: gen-oapi
        name: generate openapi schema
        entry: just gen-api-schema
        language: system
        pass_filenames: false
