[tools]
# devtools
prek = "latest"
uv     = "latest"
bun    = "latest"
# secrets
1password = "latest"
fnox = "latest"
age = "latest"
claude = "latest"

[env]
VITE_API_BASE_URL = "http://localhost:8000"
VITE_SUPABASE_URL = "https://sutnrwodqzpfvuuboksu.supabase.co"
VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY = "sb_publishable_l6XbltlqEPGu-hm18EGx-Q_qjLMqPS4"
