# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
# https://render.com/docs/blueprint-spec

services:
  # FastAPI backend
  - type: web
    name: visions-api
    rootDir: backend
    runtime: python
    region: frankfurt
    plan: free
    domains:
      - api.visions.tobydevlin.com

    # uv is already installed in render:
    # https://render.com/docs/deploys#build-command
    buildCommand: uv sync
    # preDeployCommand: uv run alembic upgrade head # needs a paid plan
    # https://render.com/docs/web-services#port-binding
    startCommand: uv run uvicorn visions.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    
    buildFilter:
      paths:
        - backend/**
      
    envVars:
      - fromGroup: visions-urls
      - key: PYTHONPATH
        value: src
      - key: DATABASE_PASSWORD
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # React + Vite frontend (static site)
  - type: web
    name: visions-web
    rootDir: frontend
    runtime: static
    domains:
      - visions.tobydevlin.com

    # bun is already installed in render:
    # https://render.com/docs/deploys#build-command
    buildCommand: bun install && bun run build
    staticPublishPath: dist

    buildFilter:
      paths:
        - frontend/**
    
    envVars:
      - fromGroup: visions-urls
      - key: VITE_SUPABASE_URL
        value: https://sutnrwodqzpfvuuboksu.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY
        sync: false

envVarGroups:
  - name: visions-urls
    envVars:
      # API 
      - key: API_BASE_URL
        value: https://api.visions.tobydevlin.com
      - key: VITE_API_BASE_URL
        value: https://api.visions.tobydevlin.com
      # UI
      - key: FRONTEND_URL
        value: https://visions.tobydevlin.com
      - key: CORS_ORIGINS
        value: '["https://visions.tobydevlin.com"]'

  - name: visions-urls-preview
    envVars:
      # API 
      - key: API_BASE_URL
        value: https://api.visions.tobydevlin.com
      - key: VITE_API_BASE_URL
        value: https://api.visions.tobydevlin.com
      # UI
      - key: FRONTEND_URL
        value: https://visions.tobydevlin.com
      - key: CORS_ORIGINS
        value: '["https://visions.tobydevlin.com"]'
