"""new model

Revision ID: 1d1ead2645bb
Revises: aefd23ac3dec
Create Date: 2026-03-04 21:52:58.642007

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d1ead2645bb"
down_revision: str | None = "aefd23ac3dec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("generationjob_style_id_fkey"), "generationjob", type_="foreignkey")
    op.drop_index(op.f("ix_designstyle_creator_id"), table_name="designstyle")
    op.drop_table("designstyle")
    op.add_column("generationjob", sa.Column("submitter_id", sa.Uuid(), nullable=False))
    op.add_column("generationjob", sa.Column("style", sqlmodel.AutoString(), nullable=False))
    op.alter_column(
        "generationjob",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "generationjob",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "generationjob",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_generationjob_style_id"), table_name="generationjob")
    op.create_index(op.f("ix_generationjob_style"), "generationjob", ["style"], unique=False)
    op.create_index(
        op.f("ix_generationjob_submitter_id"), "generationjob", ["submitter_id"], unique=False
    )
    op.create_foreign_key(None, "generationjob", "user", ["submitter_id"], ["id"])
    op.drop_column("generationjob", "status")
    op.drop_column("generationjob", "result_image_key")
    op.drop_column("generationjob", "style_id")
    op.alter_column(
        "house",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "house",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "room",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "room",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "room", ["house_id", "label"])
    op.drop_column("room", "original_image_key")
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.add_column(
        "room",
        sa.Column(
            "original_image_key", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "room",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "room",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "house",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "house",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.add_column(
        "generationjob", sa.Column("style_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "generationjob",
        sa.Column("result_image_key", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "generationjob",
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="jobstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("generationjob_style_id_fkey"), "generationjob", "designstyle", ["style_id"], ["id"]
    )
    op.drop_index(op.f("ix_generationjob_submitter_id"), table_name="generationjob")
    op.drop_index(op.f("ix_generationjob_style"), table_name="generationjob")
    op.create_index(op.f("ix_generationjob_style_id"), "generationjob", ["style_id"], unique=False)
    op.alter_column(
        "generationjob",
        "completed_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "generationjob",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "generationjob",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_column("generationjob", "style")
    op.drop_column("generationjob", "submitter_id")
    op.create_table(
        "designstyle",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
        sa.Column("preview_image_key", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("is_builtin", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("creator_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], name=op.f("designstyle_creator_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("designstyle_pkey")),
    )
    op.create_index(op.f("ix_designstyle_creator_id"), "designstyle", ["creator_id"], unique=False)
    # ### end Alembic commands ###
