"""generation_job_extra_context

Revision ID: 5e03eb6de4e2
Revises: 5fcf8f1454e2
Create Date: 2026-03-07 15:38:47.496841

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e03eb6de4e2"
down_revision: str | None = "5fcf8f1454e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generationjob",
        sa.Column("extra_context", sqlmodel.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generationjob", "extra_context")
    # ### end Alembic commands ###
