"""add generation extra context

Revision ID: 5fcf8f1454e2
Revises: a1b2c3d4e5f6
Create Date: 2026-03-07 15:33:02.642703

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fcf8f1454e2"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_house_owner_id"), table_name="property")
    op.create_index(op.f("ix_property_owner_id"), "property", ["owner_id"], unique=False)
    op.drop_index(op.f("ix_room_house_id"), table_name="room")
    op.create_index(op.f("ix_room_property_id"), "room", ["property_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_property_id"), table_name="room")
    op.create_index(op.f("ix_room_house_id"), "room", ["property_id"], unique=False)
    op.drop_index(op.f("ix_property_owner_id"), table_name="property")
    op.create_index(op.f("ix_house_owner_id"), "property", ["owner_id"], unique=False)
    # ### end Alembic commands ###
