"""sharing

Revision ID: 943963c999a0
Revises: 625ffd2a79e5
Create Date: 2026-03-14 13:23:57.244012

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "943963c999a0"
down_revision: str | None = "625ffd2a79e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "propertyshare",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("shared_with_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("property_id", "shared_with_id"),
    )
    op.create_index(
        op.f("ix_propertyshare_property_id"), "propertyshare", ["property_id"], unique=False
    )
    op.create_index(
        op.f("ix_propertyshare_shared_with_id"), "propertyshare", ["shared_with_id"], unique=False
    )
    op.add_column(
        "property", sa.Column("public", sa.Boolean(), nullable=False, server_default=sa.text("False"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("property", "public")
    op.drop_index(op.f("ix_propertyshare_shared_with_id"), table_name="propertyshare")
    op.drop_index(op.f("ix_propertyshare_property_id"), table_name="propertyshare")
    op.drop_table("propertyshare")
    # ### end Alembic commands ###
