"""tz datetimes

Revision ID: aefd23ac3dec
Revises: 
Create Date: 2026-03-03 12:09:39.391667

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aefd23ac3dec'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('email', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('picture', sqlmodel.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('designstyle',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=2000), nullable=False),
    sa.Column('preview_image_key', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designstyle_creator_id'), 'designstyle', ['creator_id'], unique=False)
    op.create_table('house',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_owner_id'), 'house', ['owner_id'], unique=False)
    op.create_table('room',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('house_id', sa.Uuid(), nullable=False),
    sa.Column('original_image_key', sqlmodel.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_house_id'), 'room', ['house_id'], unique=False)
    op.create_table('generationjob',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('style_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('result_image_key', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('error_message', sqlmodel.AutoString(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['designstyle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generationjob_room_id'), 'generationjob', ['room_id'], unique=False)
    op.create_index(op.f('ix_generationjob_style_id'), 'generationjob', ['style_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generationjob_style_id'), table_name='generationjob')
    op.drop_index(op.f('ix_generationjob_room_id'), table_name='generationjob')
    op.drop_table('generationjob')
    op.drop_index(op.f('ix_room_house_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_house_owner_id'), table_name='house')
    op.drop_table('house')
    op.drop_index(op.f('ix_designstyle_creator_id'), table_name='designstyle')
    op.drop_table('designstyle')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
