"""llm_tokens_and_credit_balance

Revision ID: f34df36e27e8
Revises: 5e03eb6de4e2
Create Date: 2026-03-09 21:40:38.844987

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f34df36e27e8"
down_revision: str | None = "5e03eb6de4e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generationjob", sa.Column("original_job_id", sa.Uuid(), nullable=True))
    op.add_column("generationjob", sa.Column("llm_model", sqlmodel.AutoString(), nullable=True))
    op.add_column(
        "generationjob", sa.Column("llm_requests", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "generationjob",
        sa.Column("llm_tool_calls", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "generationjob",
        sa.Column("llm_input_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "generationjob",
        sa.Column("llm_cache_write_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "generationjob",
        sa.Column("llm_cache_read_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "generationjob",
        sa.Column("llm_output_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        op.f("ix_generationjob_original_job_id"), "generationjob", ["original_job_id"], unique=False
    )
    op.create_foreign_key(None, "generationjob", "generationjob", ["original_job_id"], ["id"])
    op.add_column("user", sa.Column("balance", sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "balance")
    op.drop_index(op.f("ix_generationjob_original_job_id"), table_name="generationjob")
    op.drop_column("generationjob", "llm_output_tokens")
    op.drop_column("generationjob", "llm_cache_read_tokens")
    op.drop_column("generationjob", "llm_cache_write_tokens")
    op.drop_column("generationjob", "llm_input_tokens")
    op.drop_column("generationjob", "llm_tool_calls")
    op.drop_column("generationjob", "llm_requests")
    op.drop_column("generationjob", "llm_model")
    op.drop_column("generationjob", "original_job_id")
    # ### end Alembic commands ###
